name: Meetup CI
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      working-directory: ./meetup-app
      run: npm install
    - name: Run tests
      working-directory: ./meetup-app
      run: npm run test:unit